// packages/react-workspace/react-client-app/src/components/AnchorSection.tsx
import { NimbleAnchor } from '@ni/nimble-react/anchor';
import { SubContainer } from './SubContainer';

export function AnchorSection(): React.JSX.Element {
    return (
        <SubContainer label="Anchor">
            <div><NimbleAnchor href="#" appearance="prominent">Site root</NimbleAnchor></div>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/anchor-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-anchor-section',
    template: `
        <example-sub-container label="Anchor">
            <div><nimble-anchor href="#" appearance="prominent">Site root</nimble-anchor></div>
            Let's try it <nimble-anchor nimbleRouterLink="/customapp" underline-visible>using nimbleRouterLink</nimble-anchor>.
        </example-sub-container>
    `,
    standalone: false
})
export class AnchorSectionComponent {}
