// packages/react-workspace/react-client-app/src/components/AnchorStepperSection.tsx
import { NimbleStepper } from '@ni/nimble-react/stepper';
import { NimbleAnchorStep } from '@ni/nimble-react/anchor-step';
import { SubContainer } from './SubContainer';

export function AnchorStepperSection(): React.JSX.Element {
    return (
        <SubContainer label="Anchor Stepper">
            <NimbleStepper>
                <NimbleAnchorStep severity='success' href='https://nimble.ni.dev'>
                    <span slot="title">First step</span>
                    <span slot="subtitle">Something we did</span>
                </NimbleAnchorStep>
                <NimbleAnchorStep selected href='https://ni.com'>
                    <span slot="title">Second step</span>
                    <span slot="subtitle">Something we are doing</span>
                </NimbleAnchorStep>
                <NimbleAnchorStep href='https://google.com'>
                    <span slot="title">Third step</span>
                    <span slot="subtitle">Something to do</span>
                </NimbleAnchorStep>
            </NimbleStepper>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/anchor-stepper-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-anchor-stepper-section',
    template: `
        <example-sub-container label="Anchor Stepper">
            <nimble-stepper>
                <nimble-anchor-step severity="success" href="https://nimble.ni.dev">
                    <span slot="title">First step</span>
                    <span slot="subtitle">Something we did</span>
                </nimble-anchor-step>
                <nimble-anchor-step selected href="https://ni.com">
                    <span slot="title">Second step</span>
                    <span slot="subtitle">Something we are doing</span>
                </nimble-anchor-step>
                <nimble-anchor-step href="https://google.com">
                    <span slot="title">Third step</span>
                    <span slot="subtitle">Something to do</span>
                </nimble-anchor-step>
            </nimble-stepper>
        </example-sub-container>
    `,
    standalone: false
})
export class AnchorStepperSectionComponent {}
