// packages/react-workspace/react-client-app/src/components/BreadcrumbSection.tsx
import { NimbleBreadcrumb } from '@ni/nimble-react/breadcrumb';
import { NimbleBreadcrumbItem } from '@ni/nimble-react/breadcrumb-item';
import { SubContainer } from './SubContainer';

export function BreadcrumbSection(): React.JSX.Element {
    return (
        <SubContainer label="Breadcrumb">
            <NimbleBreadcrumb>
                <NimbleBreadcrumbItem href="#">Page 1</NimbleBreadcrumbItem>
                <NimbleBreadcrumbItem
                    href="#"
                >Page 2</NimbleBreadcrumbItem>
                <NimbleBreadcrumbItem>Current Page (No Link)</NimbleBreadcrumbItem>
            </NimbleBreadcrumb>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/breadcrumb-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-breadcrumb-section',
    template: `
        <example-sub-container label="Breadcrumb">
            <nimble-breadcrumb>
                <nimble-breadcrumb-item href="#">Page 1</nimble-breadcrumb-item>
                <nimble-breadcrumb-item nimbleRouterLink="/customapp">Page 2</nimble-breadcrumb-item>
                <nimble-breadcrumb-item>Current Page (No Link)</nimble-breadcrumb-item>
            </nimble-breadcrumb>
        </example-sub-container>
    `,
    standalone: false
})
export class BreadcrumbSectionComponent {}
