// packages/react-workspace/react-client-app/src/components/ButtonsSection.tsx
import { NimbleButton } from '@ni/nimble-react/button';
import { SubContainer } from './SubContainer';

export function ButtonsSection(): React.JSX.Element {
    return (
        <SubContainer label="Buttons">
            <NimbleButton appearance="outline">Outline Button</NimbleButton>
            <NimbleButton appearance="block">Block Button</NimbleButton>
            <NimbleButton appearance="ghost">Ghost Button</NimbleButton>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/buttons-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-buttons-section',
    template: `
        <example-sub-container label="Buttons">
            <nimble-button appearance="outline">Outline Button</nimble-button>
            <nimble-button appearance="block">Block Button</nimble-button>
            <nimble-button appearance="ghost">Ghost Button</nimble-button>
        </example-sub-container>
    `,
    standalone: false
})
export class ButtonsSectionComponent {}
