// packages/react-workspace/react-client-app/src/components/CardSection.tsx
import { NimbleCard } from '@ni/nimble-react/card';
import { NimbleNumberField } from '@ni/nimble-react/number-field';
import { NimbleSelect } from '@ni/nimble-react/select';
import { NimbleListOption } from '@ni/nimble-react/list-option';
import { SubContainer } from './SubContainer';

export function CardSection(): React.JSX.Element {
    return (
        <SubContainer label="Card">
            <NimbleCard>
                <span slot="title">Title of the card</span>
                <NimbleNumberField>Numeric field 1</NimbleNumberField>
                <NimbleNumberField>Numeric field 2</NimbleNumberField>
                <NimbleSelect>
                    Select
                    <NimbleListOption value="1">Option 1</NimbleListOption>
                    <NimbleListOption value="2">Option 2</NimbleListOption>
                    <NimbleListOption value="3">Option 3</NimbleListOption>
                </NimbleSelect>
            </NimbleCard>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/card-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-card-section',
    template: `
        <example-sub-container label="Card">
            <nimble-card>
                <span slot="title">Title of the card</span>
                <nimble-number-field>Numeric field 1</nimble-number-field>
                <nimble-number-field>Numeric field 2</nimble-number-field>
                <nimble-select>
                    Select
                    <nimble-list-option value="1">Option 1</nimble-list-option>
                    <nimble-list-option value="2">Option 2</nimble-list-option>
                    <nimble-list-option value="3">Option 3</nimble-list-option>
                </nimble-select>
            </nimble-card>
        </example-sub-container>
    `,
    standalone: false
})
export class CardSectionComponent {}
