// packages/react-workspace/react-client-app/src/components/DialogSection.tsx
import { useRef, useState } from 'react';
import { NimbleButton } from '@ni/nimble-react/button';
import { NimbleDialog, type Dialog, DialogUserDismissed, fromDialogRef } from '@ni/nimble-react/dialog';
import { NimbleTextField } from '@ni/nimble-react/text-field';
import { SubContainer } from './SubContainer';

export function DialogSection(): React.JSX.Element {
    const dialogRef = useRef<Dialog<string>>(null);
    const [dialogCloseReason, setDialogCloseReason] = useState('');

    function openDialog(): void {
        void (async (): Promise<void> => {
            const closeReason = await dialogRef.current?.show();
            setDialogCloseReason((closeReason === DialogUserDismissed) ? 'escape pressed' : (closeReason ?? 'unknown'));
        })();
    }

    function closeDialog(reason: string): void {
        dialogRef.current?.close(reason);
    }

    return (
        <SubContainer label="Dialog">
            <NimbleDialog
                ref={fromDialogRef(dialogRef)}
            >
                <span slot="title">This is a dialog</span>
                <div>It opened when you pushed the button</div>
                <NimbleButton slot="footer"
                    onClick={_ => closeDialog('cancel pressed')}
                >Cancel</NimbleButton>
                <NimbleButton slot="footer"
                    onClick={_ => closeDialog('OK pressed')}
                >OK</NimbleButton>
            </NimbleDialog>
            <NimbleButton
                onClick={openDialog}
            >Open Dialog</NimbleButton>
            <NimbleTextField
                value={dialogCloseReason}
            >Closed Reason</NimbleTextField>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/dialog-section.component.ts
import { Component, ViewChild } from '@angular/core';
import { NimbleDialogDirective, UserDismissed } from '@ni/nimble-angular';

@Component({
    selector: 'example-dialog-section',
    template: `
        <example-sub-container label="Dialog">
            <nimble-dialog #dialog>
                <span slot="title">This is a dialog</span>
                <div>It opened when you pushed the button</div>
                <nimble-button slot="footer" (click)="closeDialog('cancel pressed')">Cancel</nimble-button>
                <nimble-button slot="footer" (click)="closeDialog('OK pressed')">OK</nimble-button>
            </nimble-dialog>
            <nimble-button (click)="openDialog()">Open Dialog</nimble-button>
            <nimble-text-field readonly [ngModel]="dialogCloseReason">Closed Reason</nimble-text-field>
        </example-sub-container>
    `,
    standalone: false
})
export class DialogSectionComponent {
    public dialogCloseReason = '';

    @ViewChild('dialog', { read: NimbleDialogDirective }) private readonly dialog: NimbleDialogDirective<string>;

    public async openDialog(): Promise<void> {
        const closeReason = await this.dialog.show();
        this.dialogCloseReason = (closeReason === UserDismissed) ? 'escape pressed' : closeReason;
    }

    public closeDialog(reason: string): void {
        this.dialog.close(reason);
    }
}
