// packages/react-workspace/react-client-app/src/components/MenuButtonSection.tsx
import { NimbleMenu } from '@ni/nimble-react/menu';
import { NimbleMenuItem, type MenuItemChangeEvent } from '@ni/nimble-react/menu-item';
import { NimbleMenuButton } from '@ni/nimble-react/menu-button';
import { NimbleIconAdd } from '@ni/nimble-react/icons/add';
import { SubContainer } from './SubContainer';

export function MenuButtonSection(): React.JSX.Element {
    function onMenuButtonMenuChange(event: MenuItemChangeEvent): void {
        const menuItemText = event.target.innerText;
        alert(`${menuItemText} selected`);
    }

    return (
        <SubContainer label="Menu Button">
            <NimbleMenuButton>
                Menu Button
                <NimbleMenu slot="menu"
                    onChange={onMenuButtonMenuChange}
                >
                    <header>Header 1</header>
                    <NimbleMenuItem>
                        Item 1
                        <NimbleIconAdd slot="start"></NimbleIconAdd>
                    </NimbleMenuItem>
                    <NimbleMenuItem>Item 2</NimbleMenuItem>
                    <hr/>
                    <header>Header 2</header>
                    <NimbleMenuItem>Item 4</NimbleMenuItem>
                </NimbleMenu>
            </NimbleMenuButton>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/menu-button-section.component.ts
/* eslint-disable no-alert */
import { Component } from '@angular/core';
import type { MenuItem } from '@ni/nimble-angular';

@Component({
    selector: 'example-menu-button-section',
    template: `
        <example-sub-container label="Menu Button">
            <nimble-menu-button>
                Menu Button
                <nimble-menu slot="menu" (change)="onMenuButtonMenuChange($event)">
                    <header>Header 1</header>
                    <nimble-menu-item>
                        Item 1
                        <nimble-icon-add slot="start"></nimble-icon-add>
                    </nimble-menu-item>
                    <nimble-menu-item>Item 2</nimble-menu-item>
                    <hr>
                    <header>Header 2</header>
                    <nimble-menu-item>Item 4</nimble-menu-item>
                </nimble-menu>
            </nimble-menu-button>
        </example-sub-container>
    `,
    standalone: false
})
export class MenuButtonSectionComponent {
    public onMenuButtonMenuChange(event: Event): void {
        const menuItemText = (event.target as MenuItem).innerText;
        alert(`${menuItemText} selected`);
    }
}
