// packages/react-workspace/react-client-app/src/components/NumberFieldSection.tsx
import { NimbleNumberField } from '@ni/nimble-react/number-field';
import { SubContainer } from './SubContainer';

export function NumberFieldSection(): React.JSX.Element {
    return (
        <SubContainer label="Number Field">
            <NimbleNumberField appearance="underline" placeholder="Number Field" value="42">Underline Number Field</NimbleNumberField>
            <NimbleNumberField appearance="outline" placeholder="Number Field" value="42">Outline Number Field</NimbleNumberField>
            <NimbleNumberField appearance="block" placeholder="Number Field" value="42">Block Number Field</NimbleNumberField>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/number-field-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-number-field-section',
    template: `
        <example-sub-container label="Number Field">
            <nimble-number-field appearance="underline" placeholder="Number Field" value="42">Underline Number Field</nimble-number-field>
            <nimble-number-field appearance="outline" placeholder="Number Field" value="42">Outline Number Field</nimble-number-field>
            <nimble-number-field appearance="block" placeholder="Number Field" value="42">Block Number Field</nimble-number-field>
        </example-sub-container>
    `,
    standalone: false
})
export class NumberFieldSectionComponent {}
