// packages/react-workspace/react-client-app/src/components/OkAccordionItemSection.tsx
import { OkFvAccordionItem } from '@ni/ok-react/fv-accordion-item';
import { SubContainer } from './SubContainer';

export function OkAccordionItemSection(): React.JSX.Element {
    return (
        <SubContainer label="Accordion Item (Ok)">
            <OkFvAccordionItem header="Asset details" expanded>
                Calibration assets can expose operator-facing status, location, and ownership details.
            </OkFvAccordionItem>
            <OkFvAccordionItem header="Maintenance history">
                This section starts collapsed to show the default interaction state.
            </OkFvAccordionItem>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/ok-accordion-item-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-ok-accordion-item-section',
    template: `
        <example-sub-container label="Accordion Item (Ok)">
            <ok-fv-accordion-item i18n-header header="Asset details" [expanded]="true">
                Calibration assets can expose operator-facing status, location, and ownership details.
            </ok-fv-accordion-item>
            <ok-fv-accordion-item i18n-header header="Maintenance history">
                This section starts collapsed to show the default interaction state.
            </ok-fv-accordion-item>
        </example-sub-container>
    `,
    standalone: false
})
export class OkAccordionItemSectionComponent {}
