// packages/react-workspace/react-client-app/src/components/OverviewSection.tsx
import { NimbleAnchor } from '@ni/nimble-react/anchor';
import { SubContainer } from './SubContainer';

export function OverviewSection(): React.JSX.Element {
    return (
        <SubContainer label="Overview">
            Explore the components below to see the Nimble components in action.
            See the <NimbleAnchor href="https://nimble.ni.dev/storybook/">Nimble component docs</NimbleAnchor> for additional usage details.
            Navigate to the <NimbleAnchor href="../index.html">parent page</NimbleAnchor>.
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/overview-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-overview-section',
    template: `
        <example-sub-container>
            Explore the components below to see the Nimble components in action.
            See the <nimble-anchor href="https://nimble.ni.dev/storybook/">Nimble component docs</nimble-anchor> for additional usage details.
            Navigate to the <nimble-anchor href="../index.html">parent page</nimble-anchor>.
        </example-sub-container>
    `,
    standalone: false
})
export class OverviewSectionComponent {}
