// packages/react-workspace/react-client-app/src/components/RadioButtonsSection.tsx
import { useState } from 'react';
import { NimbleRadioGroup } from '@ni/nimble-react/radio-group';
import { NimbleRadio } from '@ni/nimble-react/radio';
import { NimbleTextField } from '@ni/nimble-react/text-field';
import { SubContainer } from './SubContainer';

export function RadioButtonsSection(): React.JSX.Element {
    const [selectedRadio, setSelectedRadio] = useState('mango');

    return (
        <SubContainer label="Radio Buttons">
            <NimbleRadioGroup
                value={selectedRadio}
                onChange={e => setSelectedRadio(e.target.value)}
            >
                <span slot="label">Fruit</span>
                <NimbleRadio name="fruit" value="apple"
                >Apple</NimbleRadio>
                <NimbleRadio name="fruit" value="banana"
                >Banana</NimbleRadio>
                <NimbleRadio name="fruit" value="mango"
                >Mango</NimbleRadio>
            </NimbleRadioGroup>
            <NimbleTextField
                value={selectedRadio}
            >Selected value</NimbleTextField>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/radio-buttons-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-radio-buttons-section',
    template: `
        <example-sub-container label="Radio Buttons">
            <nimble-radio-group>
                <span slot="label">Fruit</span>
                <nimble-radio name="fruit" value="apple" [(ngModel)]="selectedRadio">Apple</nimble-radio>
                <nimble-radio name="fruit" value="banana" [(ngModel)]="selectedRadio">Banana</nimble-radio>
                <nimble-radio name="fruit" value="mango" [(ngModel)]="selectedRadio">Mango</nimble-radio>
            </nimble-radio-group>
            <nimble-text-field [(ngModel)]="selectedRadio">Selected value</nimble-text-field>
        </example-sub-container>
    `,
    standalone: false
})
export class RadioButtonsSectionComponent {
    public selectedRadio = 'mango';
}
