// packages/react-workspace/react-client-app/src/components/TooltipSection.tsx
import { NimbleButton } from '@ni/nimble-react/button';
import { NimbleTooltip } from '@ni/nimble-react/tooltip';
import { SubContainer } from './SubContainer';

export function TooltipSection(): React.JSX.Element {
    return (
        <SubContainer label="Tooltip">
            <NimbleButton id="anchor1">Default</NimbleButton>
            <NimbleTooltip anchor="anchor1">Tooltip label</NimbleTooltip>
            <NimbleButton id="anchor2">Fail</NimbleButton>
            <NimbleTooltip anchor="anchor2" severity="error">Tooltip label</NimbleTooltip>
            <NimbleButton id="anchor3">Information</NimbleButton>
            <NimbleTooltip anchor="anchor3" severity="information">Tooltip label</NimbleTooltip>
            <NimbleButton id="anchor4">Fail Icon </NimbleButton>
            <NimbleTooltip anchor="anchor4" severity="error" iconVisible>Tooltip label</NimbleTooltip>
            <NimbleButton id="anchor5">Information Icon</NimbleButton>
            <NimbleTooltip anchor="anchor5" severity="information" iconVisible>Tooltip label</NimbleTooltip>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/tooltip-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-tooltip-section',
    template: `
        <example-sub-container label="Tooltip">
            <nimble-button id="anchor1">Default</nimble-button>
            <nimble-tooltip anchor="anchor1">Tooltip label</nimble-tooltip>
            <nimble-button id="anchor2">Fail</nimble-button>
            <nimble-tooltip anchor="anchor2" severity="error">Tooltip label</nimble-tooltip>
            <nimble-button id="anchor3">Information</nimble-button>
            <nimble-tooltip anchor="anchor3" severity="information">Tooltip label</nimble-tooltip>
            <nimble-button id="anchor4">Fail Icon </nimble-button>
            <nimble-tooltip anchor="anchor4" severity="error" icon-visible>Tooltip label</nimble-tooltip>
            <nimble-button id="anchor5">Information Icon</nimble-button>
            <nimble-tooltip anchor="anchor5" severity="information" icon-visible>Tooltip label</nimble-tooltip>
        </example-sub-container>
    `,
    standalone: false
})
export class TooltipSectionComponent {}
