// packages/react-workspace/react-client-app/src/components/TreeViewSection.tsx
import { NimbleTreeView } from '@ni/nimble-react/tree-view';
import { NimbleTreeItem } from '@ni/nimble-react/tree-item';
import { NimbleAnchorTreeItem } from '@ni/nimble-react/anchor-tree-item';
import { SubContainer } from './SubContainer';

export function TreeViewSection(): React.JSX.Element {
    return (
        <SubContainer label="Tree View">
            <NimbleTreeView>
                <NimbleTreeItem>
                    Parent 1
                    <NimbleTreeItem>Child 1</NimbleTreeItem>
                    <NimbleAnchorTreeItem
                        href="#"
                    >Child 2 (link)</NimbleAnchorTreeItem>
                    <NimbleTreeItem disabled>Child 3</NimbleTreeItem>
                </NimbleTreeItem>
                <NimbleTreeItem expanded>
                    Parent 2
                    <NimbleTreeItem>Child 2-1</NimbleTreeItem>
                    <NimbleTreeItem>Child 2-2</NimbleTreeItem>
                    <NimbleTreeItem>Child 2-3</NimbleTreeItem>
                </NimbleTreeItem>
            </NimbleTreeView>
        </SubContainer>
    );
}

// packages/angular-workspace/example-client-app/src/app/customapp/tree-view-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-tree-view-section',
    template: `
        <example-sub-container label="Tree View">
            <nimble-tree-view>
                <nimble-tree-item>
                    Parent 1
                    <nimble-tree-item>Child 1</nimble-tree-item>
                    <nimble-anchor-tree-item routerLink="/customapp">Child 2 (link)</nimble-anchor-tree-item>
                    <nimble-tree-item disabled>Child 3</nimble-tree-item>
                </nimble-tree-item>
                <nimble-tree-item expanded>
                    Parent 2
                    <nimble-tree-item selected>Child 2-1</nimble-tree-item>
                    <nimble-tree-item>Child 2-2</nimble-tree-item>
                    <nimble-tree-item>Child 2-3</nimble-tree-item>
                </nimble-tree-item>
            </nimble-tree-view>
        </example-sub-container>
    `,
    standalone: false
})
export class TreeViewSectionComponent {}
