// packages/angular-workspace/example-client-app/src/app/customapp/fv/fv-search-input-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-fv-search-input-section',
    template: `
        <example-sub-container label="Fv Search Input (Ok)">
            <ok-fv-search-input placeholder="Search assets" value="PXI"></ok-fv-search-input>
        </example-sub-container>
    `,
    standalone: false
})
export class FvSearchInputSectionComponent {}

// packages/react-workspace/react-client-app/src/components/Fv/FvSearchInputSection.tsx
import { OkFvSearchInput } from '@ni/ok-react/fv/search-input';
import { SubContainer } from '../SubContainer';

export function FvSearchInputSection(): React.JSX.Element {
    return (
        <SubContainer label="Fv Search Input (Ok)">
            <OkFvSearchInput
                appearance="underline"
                placeholder="Search assets"
                value="PXI"
            />
        </SubContainer>
    );
}
