// packages/angular-workspace/example-client-app/src/app/customapp/anchor-buttons-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-anchor-buttons-section',
    template: `
        <example-sub-container label="Buttons - Anchor">
            <nimble-anchor-button nimbleRouterLink="/customapp" appearance="outline">Outline Anchor Button</nimble-anchor-button>
            <nimble-anchor-button nimbleRouterLink="/customapp" appearance="block">Block Anchor Button</nimble-anchor-button>
            <nimble-anchor-button nimbleRouterLink="/customapp" appearance="ghost">Ghost Anchor Button</nimble-anchor-button>
        </example-sub-container>
    `,
    standalone: false
})
export class AnchorButtonsSectionComponent {}

// packages/react-workspace/react-client-app/src/components/AnchorButtonsSection.tsx
import { NimbleAnchorButton } from '@ni/nimble-react/anchor-button';
import { SubContainer } from './SubContainer';

export function AnchorButtonsSection(): React.JSX.Element {
    return (
        <SubContainer label="Buttons - Anchor">
            <NimbleAnchorButton
                href="#"
                appearance="outline">Outline Anchor Button</NimbleAnchorButton>
            <NimbleAnchorButton
                href="#"
                appearance="block">Block Anchor Button</NimbleAnchorButton>
            <NimbleAnchorButton
                href="#"
                appearance="ghost">Ghost Anchor Button</NimbleAnchorButton>
        </SubContainer>
    );
}
