// packages/angular-workspace/example-client-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { Theme } from '@ni/nimble-angular';

@Component({
    selector: 'example-app',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
    standalone: false
})
export class AppComponent {
    public readonly prefersColorSchemeDarkMediaQuery: MediaQueryList = window.matchMedia(
        '(prefers-color-scheme: dark)'
    );

    public readonly themes = Object.values(Theme);
    public theme: Theme = this.prefersColorSchemeDarkMediaQuery.matches ? 'dark' : 'light';
}

<nimble-theme-provider [theme]="theme">
    <nimble-label-provider-core withDefaults></nimble-label-provider-core>
    <nimble-label-provider-rich-text withDefaults></nimble-label-provider-rich-text>
    <nimble-label-provider-table withDefaults></nimble-label-provider-table>
    <div class="header">
        <nimble-select class="theme-select" appearance="frameless" [(ngModel)]="theme">
            <nimble-list-option *ngFor="let item of themes" [ngValue]="item">{{ item | titlecase}} Theme</nimble-list-option>
        </nimble-select>
    </div>
    <div class="router-outlet-wrapper">
        <router-outlet></router-outlet>
    </div>
</nimble-theme-provider>

// packages/react-workspace/react-client-app/src/components/App.tsx
import { NimbleThemeProvider, Theme } from '@ni/nimble-react/theme-provider';
import { NimbleSelect } from '@ni/nimble-react/select';
import { NimbleListOption } from '@ni/nimble-react/list-option';

import './App.scss';
import { useState } from 'react';

import { OverviewSection } from './OverviewSection';
import { AnchorSection } from './AnchorSection';
import { BannerSection } from './BannerSection';
import { BreadcrumbSection } from './BreadcrumbSection';
import { ButtonsSection } from './ButtonsSection';
import { AnchorButtonsSection } from './AnchorButtonsSection';
import { ToggleButtonsSection } from './ToggleButtonsSection';
import { CardSection } from './CardSection';
import { CardButtonSection } from './CardButtonSection';
import { CheckboxSection } from './CheckboxSection';
import { ChipSection } from './ChipSection';
import { RadioButtonsSection } from './RadioButtonsSection';
import { DialogSection } from './DialogSection';
import { DrawerSection } from './DrawerSection';
import { MenuSection } from './MenuSection';
import { MenuButtonSection } from './MenuButtonSection';
import { NumberFieldSection } from './NumberFieldSection';
import { SelectSection } from './SelectSection';
import { ComboboxSection } from './ComboboxSection';
import { RichTextEditorSection } from './RichTextEditorSection';
import { RichTextViewerSection } from './RichTextViewerSection';
import { SpinnerSection } from './SpinnerSection';
import { StepperSection } from './StepperSection';
import { SwitchSection } from './SwitchSection';
import { TableSection } from './TableSection';
import { DelayedHierarchyTableSection } from './DelayedHierarchyTableSection';
import { TabsSection } from './TabsSection';
import { AnchorTabsSection } from './AnchorTabsSection';
import { TextAreaSection } from './TextAreaSection';
import { TextFieldSection } from './TextFieldSection';
import { ToolbarSection } from './ToolbarSection';
import { TooltipSection } from './TooltipSection';
import { TreeViewSection } from './TreeViewSection';
import { ChatConversationSection } from './ChatConversationSection';
import { RectangleSection } from './RectangleSection';
import { OkButtonSection } from './OkButtonSection';

export function App(): React.JSX.Element {
    const prefersColorSchemeDarkMediaQuery: MediaQueryList = window.matchMedia(
        '(prefers-color-scheme: dark)'
    );
    const [theme, setTheme] = useState<Theme>(prefersColorSchemeDarkMediaQuery.matches ? 'dark' : 'light');

    return (
        <>
            <NimbleThemeProvider theme={theme}>
                <div className="example-root">
                    <div className="header">
                        <NimbleSelect
                            className="theme-select"
                            appearance="frameless"
                            value={theme}
                            onChange={e => setTheme(e.target.value as Theme)}
                        >
                            {Object.values(Theme).map(item => (
                                <NimbleListOption
                                    key={item}
                                    value={item}
                                >
                                    {`${item.charAt(0).toUpperCase()}${item.slice(1)}`} Theme
                                </NimbleListOption>
                            ))}
                        </NimbleSelect>
                    </div>
                    <div className="content-container-wrapper">
                        <div className="content-container">
                            <div className="container">
                                <OverviewSection />
                                <AnchorSection />
                                <BannerSection />
                                <BreadcrumbSection />
                                <ButtonsSection />
                                <AnchorButtonsSection />
                                <ToggleButtonsSection />
                                <CardSection />
                                <CardButtonSection />
                                <CheckboxSection />
                                <ChipSection />
                                <RadioButtonsSection />
                                <DialogSection />
                                <DrawerSection />
                                <MenuSection />
                                <MenuButtonSection />
                                <NumberFieldSection />
                                <SelectSection />
                                <ComboboxSection />
                                <RichTextEditorSection />
                                <RichTextViewerSection />
                                <SpinnerSection />
                                <StepperSection />
                                <SwitchSection />
                                <TableSection />
                                <DelayedHierarchyTableSection />
                                <TabsSection />
                                <AnchorTabsSection />
                                <TextAreaSection />
                                <TextFieldSection />
                                <ToolbarSection />
                                <TooltipSection />
                                <TreeViewSection />
                                <ChatConversationSection />
                                <RectangleSection />
                                <OkButtonSection />
                            </div>
                        </div>
                    </div>
                </div>
            </NimbleThemeProvider>
        </>
    );
}
