// packages/angular-workspace/example-client-app/src/app/customapp/chip-section.component.ts
/* eslint-disable no-alert */
import { Component } from '@angular/core';

@Component({
    selector: 'example-chip-section',
    template: `
        <example-sub-container label="Chip">
            <nimble-chip>Outline Chip</nimble-chip>
            <nimble-chip appearance="block">Block Chip</nimble-chip>
            <nimble-chip removable (remove)="onChipRemove()">Removable Chip</nimble-chip>
            <nimble-chip disabled>Disabled Chip</nimble-chip>
        </example-sub-container>
    `,
    standalone: false
})
export class ChipSectionComponent {
    public onChipRemove(): void {
        alert('Chip removed');
    }
}

// packages/react-workspace/react-client-app/src/components/ChipSection.tsx
import { NimbleChip } from '@ni/nimble-react/chip';
import { SubContainer } from './SubContainer';

export function ChipSection(): React.JSX.Element {
    function onChipRemove(): void {
        alert('Chip removed');
    }

    return (
        <SubContainer label="Chip">
            <NimbleChip>Outline Chip</NimbleChip>
            <NimbleChip appearance="block">Block Chip</NimbleChip>
            <NimbleChip removable onRemove={onChipRemove}>Removable Chip</NimbleChip>
            <NimbleChip disabled>Disabled Chip</NimbleChip>
        </SubContainer>
    );
}
