// packages/angular-workspace/example-client-app/src/app/customapp/combobox-section.component.ts
import { Component } from '@angular/core';
import { type OptionNotFound, OPTION_NOT_FOUND } from '@ni/nimble-angular';

interface ComboboxItem {
    first: string;
    last: string;
}

@Component({
    selector: 'example-combobox-section',
    template: `
        <example-sub-container label="Combobox">
            <nimble-combobox aria-label="Combobox" [(ngModel)]="comboboxSelectedOption" (ngModelChange)="onComboboxChange($event)" appearance="underline" autocomplete="both" placeholder="Select value...">
                Underline Combobox
                @for (item of comboboxItems; track item) {
                    <nimble-list-option [ngValue]="item">{{ item ? item.first : '' }}</nimble-list-option>
                }
            </nimble-combobox>
            <div>
                <span>
                    Last name: {{ comboboxSelectedLastName }}
                </span>
            </div>
            <nimble-combobox aria-label="Combobox" [(ngModel)]="comboboxSelectedOption" (ngModelChange)="onComboboxChange($event)" appearance="outline" autocomplete="both" placeholder="Select value...">
                Outline Combobox
                @for (item of comboboxItems; track item) {
                    <nimble-list-option [ngValue]="item">{{ item ? item.first : '' }}</nimble-list-option>
                }
            </nimble-combobox>
            <nimble-combobox aria-label="Combobox" [(ngModel)]="comboboxSelectedOption" (ngModelChange)="onComboboxChange($event)" appearance="block" autocomplete="both" placeholder="Select value...">
                Block Combobox
                @for (item of comboboxItems; track item) {
                    <nimble-list-option [ngValue]="item">{{ item ? item.first : '' }}</nimble-list-option>
                }
            </nimble-combobox>
        </example-sub-container>
    `,
    standalone: false
})
export class ComboboxSectionComponent {
    public comboboxItems: ComboboxItem[] = [
        { first: 'foo', last: 'bar' },
        { first: 'Bubba', last: 'Hotep' },
        { first: 'Mister', last: 'Smithers' }
    ];

    public comboboxSelectedOption?: ComboboxItem;
    public comboboxSelectedLastName = this.comboboxSelectedOption?.last;

    public onComboboxChange(value: ComboboxItem | OptionNotFound): void {
        if (value !== OPTION_NOT_FOUND) {
            this.comboboxSelectedLastName = value.last;
        } else {
            this.comboboxSelectedLastName = 'not found';
        }
    }
}

// packages/react-workspace/react-client-app/src/components/ComboboxSection.tsx
import { NimbleCombobox } from '@ni/nimble-react/combobox';
import { NimbleListOption } from '@ni/nimble-react/list-option';
import { SubContainer } from './SubContainer';

interface ComboboxItem {
    first: string;
    last: string;
}

const comboboxItems: ComboboxItem[] = [
    { first: 'foo', last: 'bar' },
    { first: 'Bubba', last: 'Hotep' },
    { first: 'Mister', last: 'Smithers' }
];

export function ComboboxSection(): React.JSX.Element {
    return (
        <SubContainer label="Combobox">
            <NimbleCombobox
                aria-label="Combobox"
                appearance="underline"
                autocomplete="both"
                placeholder="Select value..."
            >
                Underline Combobox
                {comboboxItems.map((item, index) => (
                    <NimbleListOption key={index}>{item.first}</NimbleListOption>
                ))}
            </NimbleCombobox>
            <NimbleCombobox
                aria-label="Combobox"
                appearance="outline"
                autocomplete="both"
                placeholder="Select value..."
            >
                Outline Combobox
                {comboboxItems.map((item, index) => (
                    <NimbleListOption key={index}>{item.first}</NimbleListOption>
                ))}
            </NimbleCombobox>
            <NimbleCombobox
                aria-label="Combobox"
                appearance="block"
                autocomplete="both"
                placeholder="Select value..."
            >
                Block Combobox
                {comboboxItems.map((item, index) => (
                    <NimbleListOption key={index}>{item.first}</NimbleListOption>
                ))}
            </NimbleCombobox>
        </SubContainer>
    );
}
