// packages/angular-workspace/example-client-app/src/app/customapp/drawer-section.component.ts
import { Component, ViewChild } from '@angular/core';
import { DrawerLocation, NimbleDrawerDirective, UserDismissed } from '@ni/nimble-angular';

@Component({
    selector: 'example-drawer-section',
    template: `
        <example-sub-container label="Drawer">
            <nimble-drawer #drawer [location]="drawerLocation">
                <header>This is a drawer</header>
                <section>
                    <p style="height: 1000px;">It opened when you pushed the button</p>
                    <p>This is the bottom!</p>
                </section>
                <footer class="drawer-footer">
                    <nimble-button appearance="ghost" (click)="closeDrawer('cancel pressed')">Cancel</nimble-button>
                    <nimble-button (click)="closeDrawer('OK pressed')">OK</nimble-button>
                </footer>
            </nimble-drawer>
            <nimble-button (click)="openDrawer()">Open Drawer</nimble-button>
            <nimble-text-field readonly [ngModel]="drawerCloseReason">Closed Reason</nimble-text-field>
            <nimble-select class="drawer-location-select" [(ngModel)]="drawerLocation">
                Drawer Location
                <nimble-list-option [value]="drawerLocations.left">Drawer: Left-side</nimble-list-option>
                <nimble-list-option [value]="drawerLocations.right">Drawer: Right-side</nimble-list-option>
            </nimble-select>
        </example-sub-container>
    `,
    styles: [`
        @use '@ni/nimble-angular/styles/tokens' as *;
        .drawer-location-select { width: 200px; }
        .drawer-footer { gap: $ni-nimble-standard-padding; }
        nimble-drawer p { color: $ni-nimble-body-font-color; }
    `],
    standalone: false
})
export class DrawerSectionComponent {
    public drawerCloseReason = '';
    public drawerLocation: DrawerLocation = DrawerLocation.right;
    public drawerLocations = DrawerLocation;

    @ViewChild('drawer', { read: NimbleDrawerDirective }) private readonly drawer: NimbleDrawerDirective<string>;

    public async openDrawer(): Promise<void> {
        const closeReason = await this.drawer.show();
        this.drawerCloseReason = (closeReason === UserDismissed) ? 'escape pressed' : closeReason;
    }

    public closeDrawer(reason: string): void {
        this.drawer.close(reason);
    }
}

// packages/react-workspace/react-client-app/src/components/DrawerSection.tsx
import { useRef, useState } from 'react';
import { NimbleButton } from '@ni/nimble-react/button';
import { NimbleDrawer, type Drawer, DrawerUserDismissed, DrawerLocation, fromDrawerRef } from '@ni/nimble-react/drawer';
import { NimbleTextField } from '@ni/nimble-react/text-field';
import { NimbleSelect } from '@ni/nimble-react/select';
import { NimbleListOption } from '@ni/nimble-react/list-option';
import { SubContainer } from './SubContainer';

export function DrawerSection(): React.JSX.Element {
    const drawerRef = useRef<Drawer<string>>(null);
    const [drawerCloseReason, setDrawerCloseReason] = useState('');
    const [drawerLocation, setDrawerLocation] = useState<DrawerLocation>(DrawerLocation.right);

    function openDrawer(): void {
        void (async (): Promise<void> => {
            const closeReason = await drawerRef.current?.show();
            setDrawerCloseReason((closeReason === DrawerUserDismissed) ? 'escape pressed' : (closeReason ?? 'unknown'));
        })();
    }

    function closeDrawer(reason: string): void {
        drawerRef.current?.close(reason);
    }

    return (
        <SubContainer label="Drawer">
            <NimbleDrawer
                ref={fromDrawerRef(drawerRef)}
                location={drawerLocation}
            >
                <header>This is a drawer</header>
                <section>
                    <p style={{ height: '1000px' }}>It opened when you pushed the button</p>
                    <p>This is the bottom!</p>
                </section>
                <footer className="drawer-footer">
                    <NimbleButton appearance="ghost"
                        onClick={() => closeDrawer('cancel pressed')}
                    >Cancel</NimbleButton>
                    <NimbleButton
                        onClick={() => closeDrawer('OK pressed')}
                    >OK</NimbleButton>
                </footer>
            </NimbleDrawer>
            <NimbleButton
                onClick={openDrawer}
            >Open Drawer</NimbleButton>
            <NimbleTextField
                readOnly
                value={drawerCloseReason}
            >Closed Reason</NimbleTextField>
            <NimbleSelect className="drawer-location-select"
                value={drawerLocation}
                onChange={e => setDrawerLocation(e.target.value === DrawerLocation.left ? DrawerLocation.left : DrawerLocation.right)}
            >
                Drawer Location
                <NimbleListOption
                    value={DrawerLocation.left}
                >Drawer: Left-side</NimbleListOption>
                <NimbleListOption
                    value={DrawerLocation.right}
                >Drawer: Right-side</NimbleListOption>
            </NimbleSelect>
        </SubContainer>
    );
}
