// packages/angular-workspace/example-client-app/src/app/customapp/menu-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-menu-section',
    template: `
        <example-sub-container label="Menu">
            <nimble-menu>
                <header>Header 1</header>
                <nimble-menu-item>
                    Item 1
                    <nimble-icon-add slot="start"></nimble-icon-add>
                </nimble-menu-item>
                <nimble-menu-item>Item 2</nimble-menu-item>
                <hr>
                <header>Header 2</header>
                <nimble-menu-item>Item 4</nimble-menu-item>
                <nimble-anchor-menu-item routerLink="/customapp">Item 5 (link)</nimble-anchor-menu-item>
            </nimble-menu>
        </example-sub-container>
    `,
    standalone: false
})
export class MenuSectionComponent {}

// packages/react-workspace/react-client-app/src/components/MenuSection.tsx
import { NimbleMenu } from '@ni/nimble-react/menu';
import { NimbleMenuItem } from '@ni/nimble-react/menu-item';
import { NimbleAnchorMenuItem } from '@ni/nimble-react/anchor-menu-item';
import { NimbleIconAdd } from '@ni/nimble-react/icons/add';
import { SubContainer } from './SubContainer';

export function MenuSection(): React.JSX.Element {
    return (
        <SubContainer label="Menu">
            <NimbleMenu>
                <header>Header 1</header>
                <NimbleMenuItem>
                    Item 1
                    <NimbleIconAdd slot="start"></NimbleIconAdd>
                </NimbleMenuItem>
                <NimbleMenuItem>Item 2</NimbleMenuItem>
                <hr />
                <header>Header 2</header>
                <NimbleMenuItem>Item 4</NimbleMenuItem>
                <NimbleAnchorMenuItem
                    href="#"
                >Item 5 (link)</NimbleAnchorMenuItem>
            </NimbleMenu>
        </SubContainer>
    );
}
