// packages/angular-workspace/example-client-app/src/app/customapp/ok-fv-search-input-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-ok-fv-search-input-section',
    template: `
        <example-sub-container label="FV Search Input (Ok)">
            <ok-fv-search-input placeholder="Search assets" value="PXI"></ok-fv-search-input>
        </example-sub-container>
    `,
    standalone: false
})
export class OkFvSearchInputSectionComponent {}

// packages/react-workspace/react-client-app/src/components/OkFvSearchInputSection.tsx
import { OkFvSearchInput } from '@ni/ok-react/fv-search-input';
import { SubContainer } from './SubContainer';

export function OkFvSearchInputSection(): React.JSX.Element {
    return (
        <SubContainer label="FV Search Input (Ok)">
            <OkFvSearchInput
                appearance="underline"
                placeholder="Search assets"
                value="PXI"
            />
        </SubContainer>
    );
}
