// packages/angular-workspace/example-client-app/src/app/customapp/spinner-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-spinner-section',
    template: `
        <example-sub-container label="Spinner">
            <nimble-spinner aria-label="Loading example content"></nimble-spinner>
        </example-sub-container>
    `,
    standalone: false
})
export class SpinnerSectionComponent {}

// packages/react-workspace/react-client-app/src/components/SpinnerSection.tsx
import { NimbleSpinner } from '@ni/nimble-react/spinner';
import { SubContainer } from './SubContainer';

export function SpinnerSection(): React.JSX.Element {
    return (
        <SubContainer label="Spinner">
            <NimbleSpinner aria-label="Loading example content"></NimbleSpinner>
        </SubContainer>
    );
}
