// packages/angular-workspace/example-client-app/src/app/customapp/switch-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-switch-section',
    template: `
        <example-sub-container label="Switch">
            <nimble-switch>Switch</nimble-switch>
            <nimble-switch checked>
                Switch with checked/unchecked messages
                <span slot="unchecked-message">Off</span>
                <span slot="checked-message">On</span>
            </nimble-switch>
        </example-sub-container>
    `,
    standalone: false
})
export class SwitchSectionComponent {}

// packages/react-workspace/react-client-app/src/components/SwitchSection.tsx
import { NimbleSwitch } from '@ni/nimble-react/switch';
import { SubContainer } from './SubContainer';

export function SwitchSection(): React.JSX.Element {
    return (
        <SubContainer label="Switch">
            <NimbleSwitch>Switch</NimbleSwitch>
            <NimbleSwitch checked>
                Switch with checked/unchecked messages
                <span slot="unchecked-message">Off</span>
                <span slot="checked-message">On</span>
            </NimbleSwitch>
        </SubContainer>
    );
}
