// packages/angular-workspace/example-client-app/src/app/customapp/table-section.component.ts
import { Component } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import type { TableRecord } from '@ni/nimble-angular/table';
import type { MenuButtonColumnToggleEventDetail } from '@ni/nimble-angular/table-column/menu-button';

const colors = ['Red', 'Green', 'Blue', 'Black', 'Yellow'] as const;
type Color = typeof colors[number];

interface SimpleTableRecord extends TableRecord {
    id: string;
    parentId?: string;
    stringValue1: string;
    stringValue2: string;
    href?: string;
    linkLabel?: string;
    date: number;
    statusCode: number;
    result: string;
    number: number;
    duration: number;
    color: Color;
}

@Component({
    selector: 'example-table-section',
    template: `
        <example-sub-container label="Table">
            <nimble-table [data$]="tableData$" id-field-name="id" parent-id-field-name="parentId" selection-mode="multiple">
                <nimble-table-column-text
                    field-name="stringValue1"
                    action-menu-slot="action-menu"
                    action-menu-label="Action menu"
                    fractional-width="2"
                    min-pixel-width="300"
                    sort-direction="ascending"
                    sort-index="0"
                >
                    <nimble-icon-check title="String 1"></nimble-icon-check>
                </nimble-table-column-text>
                <nimble-table-column-anchor
                    href-field-name="href"
                    label-field-name="linkLabel"
                >
                    Link
                </nimble-table-column-anchor>
                <nimble-table-column-date-text
                    field-name="date"
                >
                    Date
                </nimble-table-column-date-text>
                <nimble-table-column-mapping
                    field-name="statusCode"
                    key-type="number"
                >
                    <nimble-mapping-text key="100" text="Status message 1"></nimble-mapping-text>
                    <nimble-mapping-text key="101" text="Status message 2"></nimble-mapping-text>
                    Status
                </nimble-table-column-mapping>
                <nimble-table-column-mapping
                    field-name="result"
                    key-type="string"
                    width-mode="icon-size"
                >
                    <nimble-mapping-icon
                        key="success"
                        text="Success"
                        icon="nimble-icon-check"
                        severity="success"
                        text-hidden>
                    </nimble-mapping-icon>
                    <nimble-mapping-spinner
                        key="calculating"
                        text="Calculating"
                        text-hidden>
                    </nimble-mapping-spinner>
                    <nimble-mapping-empty
                        key="unknown"
                        text="Unknown">
                    </nimble-mapping-empty>
                    <nimble-icon-xmark-check title="Result"></nimble-icon-xmark-check>
                </nimble-table-column-mapping>
                <nimble-table-column-number-text
                    field-name="number"
                >
                    Number
                </nimble-table-column-number-text>
                <nimble-table-column-duration-text
                    field-name="duration"
                >
                    Duration
                </nimble-table-column-duration-text>
                <nimble-table-column-text field-name="stringValue2" min-pixel-width="400" group-index="0">String 2</nimble-table-column-text>
                <nimble-table-column-menu-button field-name="color" menu-slot="color-menu"
                    (menu-button-column-beforetoggle)="onMenuButtonColumnBeforeToggle($event)"
                >
                    Color
                </nimble-table-column-menu-button>

                <nimble-menu slot="action-menu">
                    <nimble-menu-item>Item 1</nimble-menu-item>
                    <nimble-menu-item>Item 2</nimble-menu-item>
                    <nimble-menu-item>Item 3</nimble-menu-item>
                </nimble-menu>

                <nimble-menu slot="color-menu">
                    @for (color of possibleColors; track color) {
                        <nimble-menu-item (change)="onColorSelected(color)">
                            @if (color === currentColor) {
                                <nimble-icon-check slot="start"></nimble-icon-check>
                            }
                            {{ color }}
                        </nimble-menu-item>
                    }
                </nimble-menu>
            </nimble-table>
            <nimble-button class="add-table-row-button" (click)="addTableRows(10)">Add rows</nimble-button>
        </example-sub-container>
    `,
    styles: [`
        @use '@ni/nimble-angular/styles/tokens' as *;
        nimble-table { max-height: 480px; }
        .add-table-row-button { margin-top: $ni-nimble-small-padding; }
    `],
    standalone: false
})
export class TableSectionComponent {
    public possibleColors = colors;
    public currentColor?: Color;
    public openMenuButtonColumnRecordId?: string;
    public readonly tableData$: Observable<SimpleTableRecord[]>;
    private readonly tableDataSubject = new BehaviorSubject<SimpleTableRecord[]>([]);

    public constructor() {
        this.tableData$ = this.tableDataSubject.asObservable();
        this.addTableRows(10);
    }

    public addTableRows(numberOfRowsToAdd: number): void {
        const tableData = this.tableDataSubject.value;
        const possibleStatuses = ['success', 'calculating', 'unknown'];
        for (let i = 0; i < numberOfRowsToAdd; i++) {
            tableData.push({
                id: tableData.length.toString(),
                parentId: (tableData.length >= 4 ? (tableData.length % 4).toString() : undefined),
                stringValue1: `new string ${tableData.length}`,
                stringValue2: `bar ${tableData.length}`,
                href: '/customapp',
                linkLabel: 'Link',
                date: (tableData.length % 2 === 0) ? new Date(2023, 7, 16, 3, 56, 11).valueOf() : new Date(2022, 2, 7, 20, 28, 41).valueOf(),
                statusCode: (tableData.length % 2 === 0) ? 100 : 101,
                result: possibleStatuses[tableData.length % 3],
                number: tableData.length / 10,
                duration: tableData.length * 1000 * (1.1 + 2 * 60 + 3 * 3600),
                color: colors[tableData.length % colors.length]
            });
        }
        this.tableDataSubject.next(tableData);
    }

    public onMenuButtonColumnBeforeToggle(event: Event): void {
        const customEvent = event as CustomEvent<MenuButtonColumnToggleEventDetail>;
        if (customEvent.detail.newState) {
            this.openMenuButtonColumnRecordId = customEvent.detail.recordId;
            const tableData = this.tableDataSubject.value;
            const currentRecord = tableData.find(record => record.id === customEvent.detail.recordId)!;
            this.currentColor = currentRecord.color;
        }
    }

    public onColorSelected(color: Color): void {
        const data = this.tableDataSubject.value;
        const recordToUpdate = data.find(record => record.id === this.openMenuButtonColumnRecordId);
        if (!recordToUpdate) {
            return;
        }
        recordToUpdate.color = color;
        this.tableDataSubject.next(data);
    }
}

// packages/react-workspace/react-client-app/src/components/TableSection.tsx
import { useState, useRef, useEffect } from 'react';
import { NimbleButton } from '@ni/nimble-react/button';
import { NimbleMenu } from '@ni/nimble-react/menu';
import { NimbleMenuItem } from '@ni/nimble-react/menu-item';
import { NimbleTable, type Table, type TableRecord, fromTableRef } from '@ni/nimble-react/table';
import { NimbleTableColumnText } from '@ni/nimble-react/table-column/text';
import { NimbleTableColumnAnchor } from '@ni/nimble-react/table-column/anchor';
import { NimbleTableColumnDateText } from '@ni/nimble-react/table-column/date-text';
import { NimbleTableColumnMapping } from '@ni/nimble-react/table-column/mapping';
import { NimbleMappingText } from '@ni/nimble-react/mapping/text';
import { NimbleMappingIcon } from '@ni/nimble-react/mapping/icon';
import { NimbleMappingSpinner } from '@ni/nimble-react/mapping/spinner';
import { NimbleMappingEmpty } from '@ni/nimble-react/mapping/empty';
import { NimbleTableColumnNumberText } from '@ni/nimble-react/table-column/number-text';
import { NimbleTableColumnDurationText } from '@ni/nimble-react/table-column/duration-text';
import { NimbleTableColumnMenuButton, type TableColumnMenuButtonBeforeToggleEvent } from '@ni/nimble-react/table-column/menu-button';
import { iconCheckTag, NimbleIconCheck } from '@ni/nimble-react/icons/check';
import { NimbleIconXmarkCheck } from '@ni/nimble-react/icons/xmark-check';
import { SubContainer } from './SubContainer';

const colors = ['Red', 'Green', 'Blue', 'Black', 'Yellow'] as const;
type Color = typeof colors[number];

interface SimpleTableRecord extends TableRecord {
    [key: string]: string | number | boolean | undefined;
    id: string;
    parentId?: string;
    stringValue1: string;
    stringValue2: string;
    href?: string;
    linkLabel?: string;
    date: number;
    statusCode: number;
    result: string;
    number: number;
    duration: number;
    color: Color;
}

export function TableSection(): React.JSX.Element {
    const [tableData, setTableData] = useState<SimpleTableRecord[]>(() => {
        const possibleStatuses = ['success', 'calculating', 'unknown'];
        const initialRows: SimpleTableRecord[] = [];
        for (let i = 0; i < 10; i++) {
            initialRows.push({
                id: i.toString(),
                parentId: (i >= 4 ? (i % 4).toString() : undefined),
                stringValue1: `new string ${i}`,
                stringValue2: `bar ${i}`,
                href: '/customapp',
                linkLabel: 'Link',
                date: (i % 2 === 0) ? new Date(2023, 7, 16, 3, 56, 11).valueOf() : new Date(2022, 2, 7, 20, 28, 41).valueOf(),
                statusCode: (i % 2 === 0) ? 100 : 101,
                result: possibleStatuses[i % 3],
                number: i / 10,
                duration: i * 1000 * (1.1 + 2 * 60 + 3 * 3600),
                color: colors[i % colors.length]
            });
        }
        return initialRows;
    });
    const [currentColor, setCurrentColor] = useState<Color | undefined>(undefined);
    const [openMenuButtonColumnRecordId, setOpenMenuButtonColumnRecordId] = useState<string | undefined>(undefined);
    const tableRef = useRef<Table<SimpleTableRecord>>(null);

    function addTableRows(numberOfRowsToAdd: number): void {
        const possibleStatuses = ['success', 'calculating', 'unknown'];
        const newRows: SimpleTableRecord[] = [];
        for (let i = 0; i < numberOfRowsToAdd; i++) {
            const currentLength = tableData.length + i;
            newRows.push({
                id: currentLength.toString(),
                parentId: (currentLength >= 4 ? (currentLength % 4).toString() : undefined),
                stringValue1: `new string ${currentLength}`,
                stringValue2: `bar ${currentLength}`,
                href: '/customapp',
                linkLabel: 'Link',
                date: (currentLength % 2 === 0) ? new Date(2023, 7, 16, 3, 56, 11).valueOf() : new Date(2022, 2, 7, 20, 28, 41).valueOf(),
                statusCode: (currentLength % 2 === 0) ? 100 : 101,
                result: possibleStatuses[currentLength % 3],
                number: currentLength / 10,
                duration: currentLength * 1000 * (1.1 + 2 * 60 + 3 * 3600),
                color: colors[currentLength % colors.length]
            });
        }
        setTableData([...tableData, ...newRows]);
    }

    function onMenuButtonColumnBeforeToggle(event: TableColumnMenuButtonBeforeToggleEvent): void {
        if (event.detail.newState) {
            setOpenMenuButtonColumnRecordId(event.detail.recordId);
            const currentRecord = tableData.find(record => record.id === event.detail.recordId);
            if (currentRecord) {
                setCurrentColor(currentRecord.color);
            }
        }
    }

    function onColorSelected(color: Color): void {
        const recordToUpdate = tableData.find(record => record.id === openMenuButtonColumnRecordId);
        if (recordToUpdate) {
            recordToUpdate.color = color;
            setTableData([...tableData]);
        }
    }

    useEffect(() => {
        void ((async (): Promise<void> => {
            await tableRef.current?.setData(tableData);
        })());
    }, [tableData]);

    return (
        <SubContainer label="Table">
            <NimbleTable
                ref={fromTableRef(tableRef)}
                idFieldName="id"
                parentIdFieldName="parentId"
                selectionMode="multiple"
                style={{ height: '400px' }}>
                <NimbleTableColumnText
                    fieldName="stringValue1"
                    actionMenuSlot="action-menu"
                    actionMenuLabel="Action menu"
                    fractionalWidth={2}
                    minPixelWidth={300}
                    sortDirection="ascending"
                    sortIndex={0}>
                    <NimbleIconCheck title="String 1"></NimbleIconCheck>
                </NimbleTableColumnText>
                <NimbleTableColumnAnchor
                    hrefFieldName="href"
                    labelFieldName="linkLabel">
                    Link
                </NimbleTableColumnAnchor>
                <NimbleTableColumnDateText fieldName="date">
                    Date
                </NimbleTableColumnDateText>
                <NimbleTableColumnMapping
                    fieldName="statusCode"
                    keyType="number">
                    <NimbleMappingText keyValue="100" text="Status message 1"></NimbleMappingText>
                    <NimbleMappingText keyValue="101" text="Status message 2"></NimbleMappingText>
                    Status
                </NimbleTableColumnMapping>
                <NimbleTableColumnMapping
                    fieldName="result"
                    keyType="string"
                    widthMode="icon-size">
                    <NimbleMappingIcon
                        keyValue="success"
                        text="Success"
                        icon={iconCheckTag}
                        severity="success"
                        textHidden>
                    </NimbleMappingIcon>
                    <NimbleMappingSpinner
                        keyValue="calculating"
                        text="Calculating"
                        textHidden>
                    </NimbleMappingSpinner>
                    <NimbleMappingEmpty
                        keyValue="unknown"
                        text="Unknown">
                    </NimbleMappingEmpty>
                    <NimbleIconXmarkCheck title="Result"></NimbleIconXmarkCheck>
                </NimbleTableColumnMapping>
                <NimbleTableColumnNumberText fieldName="number">
                    Number
                </NimbleTableColumnNumberText>
                <NimbleTableColumnDurationText fieldName="duration">
                    Duration
                </NimbleTableColumnDurationText>
                <NimbleTableColumnText fieldName="stringValue2" minPixelWidth={400} groupIndex={0}>
                    String 2
                </NimbleTableColumnText>
                <NimbleTableColumnMenuButton
                    fieldName="color"
                    menuSlot="color-menu"
                    onBeforeToggle={onMenuButtonColumnBeforeToggle}>
                    Color
                </NimbleTableColumnMenuButton>

                <NimbleMenu slot="action-menu">
                    <NimbleMenuItem>Item 1</NimbleMenuItem>
                    <NimbleMenuItem>Item 2</NimbleMenuItem>
                    <NimbleMenuItem>Item 3</NimbleMenuItem>
                </NimbleMenu>

                <NimbleMenu slot="color-menu">
                    {colors.map(color => (
                        <NimbleMenuItem
                            key={color}
                            onChange={() => onColorSelected(color)}>
                            {color === currentColor && (
                                <NimbleIconCheck slot="start"></NimbleIconCheck>
                            )}
                            {color}
                        </NimbleMenuItem>
                    ))}
                </NimbleMenu>
            </NimbleTable>
            <NimbleButton className="add-table-row-button"
                onClick={() => addTableRows(10)}
            >Add rows</NimbleButton>
            <div>Row count: {tableData.length}</div>
        </SubContainer>
    );
}
