// packages/angular-workspace/example-client-app/src/app/customapp/tabs-section.component.ts
/* eslint-disable no-alert */
import { Component } from '@angular/core';

@Component({
    selector: 'example-tabs-section',
    template: `
        <example-sub-container label="Tabs">
            <nimble-tabs [(activeid)]="activeTabId">
                <nimble-tab id="tab-1">Tab 1</nimble-tab>
                <nimble-tab id="tab-2">Tab 2</nimble-tab>
                <nimble-tab id="tab-3" disabled>Tab 3 (Disabled)</nimble-tab>
                <nimble-tabs-toolbar>
                    <nimble-button (click)="onTabToolbarButtonClick()">Toolbar button</nimble-button>
                </nimble-tabs-toolbar>
                <nimble-tab-panel>
                    <div class="container-label">Tab 1 content</div>
                </nimble-tab-panel>
                <nimble-tab-panel>
                    <div class="container-label">Tab 2 content</div>
                </nimble-tab-panel>
                <nimble-tab-panel>
                    <div class="container-label">Tab 3 content</div>
                </nimble-tab-panel>
            </nimble-tabs>
            <label id="activeTabLabel">
                Active tab:
            </label>
            <nimble-select [(ngModel)]="activeTabId" aria-labelledby="activeTabLabel">
                <nimble-list-option value="tab-1">Tab 1</nimble-list-option>
                <nimble-list-option value="tab-2">Tab 2</nimble-list-option>
                <nimble-list-option value="tab-3">Tab 3</nimble-list-option>
            </nimble-select>
        </example-sub-container>
    `,
    styles: [`
        @use '@ni/nimble-angular/styles/tokens' as *;
        .container-label {
            font: $ni-nimble-group-header-font;
            color: $ni-nimble-group-header-font-color;
            padding-bottom: $ni-nimble-standard-padding;
        }
    `],
    standalone: false
})
export class TabsSectionComponent {
    public activeTabId = 'tab-1';

    public onTabToolbarButtonClick(): void {
        alert('Tab toolbar button clicked');
    }
}

// packages/react-workspace/react-client-app/src/components/TabsSection.tsx
import { useState } from 'react';
import { NimbleButton } from '@ni/nimble-react/button';
import { NimbleTabs } from '@ni/nimble-react/tabs';
import { NimbleTab } from '@ni/nimble-react/tab';
import { NimbleTabsToolbar } from '@ni/nimble-react/tabs-toolbar';
import { NimbleTabPanel } from '@ni/nimble-react/tab-panel';
import { NimbleSelect } from '@ni/nimble-react/select';
import { NimbleListOption } from '@ni/nimble-react/list-option';
import { SubContainer } from './SubContainer';

export function TabsSection(): React.JSX.Element {
    const [activeTabId, setActiveTabId] = useState('tab-1');

    function onTabToolbarButtonClick(): void {
        alert('Tab toolbar button clicked');
    }

    return (
        <SubContainer label="Tabs">
            <NimbleTabs
                activeid={activeTabId}
                onChange={e => setActiveTabId(e.target.activeid)}
            >
                <NimbleTab id="tab-1">Tab 1</NimbleTab>
                <NimbleTab id="tab-2">Tab 2</NimbleTab>
                <NimbleTab id="tab-3" disabled>Tab 3 (Disabled)</NimbleTab>
                <NimbleTabsToolbar>
                    <NimbleButton
                        onClick={onTabToolbarButtonClick}
                    >Toolbar button</NimbleButton>
                </NimbleTabsToolbar>
                <NimbleTabPanel>
                    <div className="container-label">Tab 1 content</div>
                </NimbleTabPanel>
                <NimbleTabPanel>
                    <div className="container-label">Tab 2 content</div>
                </NimbleTabPanel>
                <NimbleTabPanel>
                    <div className="container-label">Tab 3 content</div>
                </NimbleTabPanel>
            </NimbleTabs>
            <label id="activeTabLabel">
                Active tab:
            </label>
            <NimbleSelect
                value={activeTabId}
                onChange={e => setActiveTabId(e.target.value)}
                aria-labelledby="activeTabLabel">
                <NimbleListOption value="tab-1">Tab 1</NimbleListOption>
                <NimbleListOption value="tab-2">Tab 2</NimbleListOption>
                <NimbleListOption value="tab-3">Tab 3</NimbleListOption>
            </NimbleSelect>
        </SubContainer>
    );
}
