// packages/angular-workspace/example-client-app/src/app/customapp/text-field-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-text-field-section',
    template: `
        <example-sub-container label="Text Field">
            <nimble-text-field appearance="underline" placeholder="Text Field" value="Here is text!">Underline Text Field</nimble-text-field>
            <nimble-text-field appearance="outline" placeholder="Text Field" value="Here is text!">Outline Text Field</nimble-text-field>
            <nimble-text-field appearance="block" placeholder="Text Field" value="Here is text!">Block Text Field</nimble-text-field>
        </example-sub-container>
    `,
    standalone: false
})
export class TextFieldSectionComponent {}

// packages/react-workspace/react-client-app/src/components/TextFieldSection.tsx
import { NimbleTextField } from '@ni/nimble-react/text-field';
import { SubContainer } from './SubContainer';

export function TextFieldSection(): React.JSX.Element {
    return (
        <SubContainer label="Text Field">
            <NimbleTextField appearance="underline" placeholder="Text Field" value="Here is text!">Underline Text Field</NimbleTextField>
            <NimbleTextField appearance="outline" placeholder="Text Field" value="Here is text!">Outline Text Field</NimbleTextField>
            <NimbleTextField appearance="block" placeholder="Text Field" value="Here is text!">Block Text Field</NimbleTextField>
        </SubContainer>
    );
}
