// packages/angular-workspace/example-client-app/src/app/customapp/toggle-buttons-section.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'example-toggle-buttons-section',
    template: `
        <example-sub-container label="Buttons - Toggle">
            <nimble-toggle-button appearance="outline">Outline Toggle Button</nimble-toggle-button>
            <nimble-toggle-button appearance="block">Block Toggle Button</nimble-toggle-button>
            <nimble-toggle-button appearance="ghost">Ghost Toggle Button</nimble-toggle-button>
        </example-sub-container>
    `,
    standalone: false
})
export class ToggleButtonsSectionComponent {}

// packages/react-workspace/react-client-app/src/components/ToggleButtonsSection.tsx
import { NimbleToggleButton } from '@ni/nimble-react/toggle-button';
import { SubContainer } from './SubContainer';

export function ToggleButtonsSection(): React.JSX.Element {
    return (
        <SubContainer label="Buttons - Toggle">
            <NimbleToggleButton appearance="outline">Outline Toggle Button</NimbleToggleButton>
            <NimbleToggleButton appearance="block">Block Toggle Button</NimbleToggleButton>
            <NimbleToggleButton appearance="ghost">Ghost Toggle Button</NimbleToggleButton>
        </SubContainer>
    );
}
